### ISSUE TITLE
With regard to environment reset

### ISSUE THREAD

**Issue by dgjun32** [ServiceNow/WorkArena#22]
After the entire evaluation, how can I reset the whole environment?

Do I have to release the instance and request a new one? or just run the 'workarena-install' command with existing instance?

**Comment by aldro61** [comment]
If you want to completely reset the environment, you need to release your instance, create a new one, and re-run workarena-install. 

However, note that this is not necessary. We take measures to keep tasks isolated from one another:
- Each task is executed in a new user with a random name (data doesn't transport across users)
- Each task has a teardown function that cleans up any data created during the task execution

Hope this helps!

**Comment by dgjun32** [comment]
With respect to the teardown function in task, can you specify the usage of the function with more details?

**Comment by aldro61** [comment]
This function is called after each episode to make sure the task leaves no trace in the database. It wipes any data that was created to make the task possible (by the setup function) or data created by the agent.
