### ISSUE TITLE
Maximize investment return stasks not ending on wrong answer

### ISSUE THREAD

**Issue by ThibaultLSDC** [ServiceNow/WorkArena#25]
Max return investment tasks allow wrong answers without ending the episode.
cf https://github.com/ServiceNow/WorkArena/blob/b11908298f2e870a18e4a25cfa972ccd33cac3de/src/browsergym/workarena/tasks/compositional/maximize_investment_return.py#L240-L245
Is this intended ? @jardinetsouffleton

**Comment by aldro61** [comment]
I think this is the expected behavior. We only terminate a task with a failure if incorrect information or modifications are pushed to the database (eg, deleting the wrong record).
