### ISSUE TITLE
Timeout error in env.step()

### ISSUE THREAD

**Issue by dgjun32** [ServiceNow/WorkArena#26]
in 1st and 2nd task in "workarena.servicenow.order-developer-laptop", admissible action (e.g., click checkbox) results in Timeout Error. Is there any solution?

**Comment by gasse** [comment]
I don't think this is a bug. The way the UI is implemented, in these tasks the checkboxes can not be interacted with. The task is still feasible by clicking the checkboxes' label instead. Our GPT4 agent usually figures this out and clicks the label after clicking the checkbox unsuccessfully.

**Comment by dgjun32** [comment]
Oh, I see, I thought it was a bug but It seems checkboxes are not clickable..! Thank you very much.

**Comment by gasse** [comment]
Yes it's something we noticed also a while ago, we decided not do do anything about it. It's a weird UI behavior but representative of entreprise software. You're welcome!
