### ISSUE TITLE
Oracle functions for each task

### ISSUE THREAD

**Issue by dgjun32** [ServiceNow/WorkArena#27]
<img width="591" alt="image" src="https://github.com/user-attachments/assets/e69d54e6-05f5-44e7-b38d-32ad525da809">

Hello, I have a question about the oracle function corresponding to each task.
As mentioned in the paper, It seems there is a handcrafted solution for each task.

However, I am not sure how to get such a solution as a sequence of actions. Is it possible to acquire oracle action sequence like: ?
```
click('a10')
fill('...', 'a32')
.
.
.
click('a56')
```

**Comment by aldro61** [comment]
Yes, you can start from this script and modify it to fit your needs. This currently extracts observation-action traces using the oracle functions for any task. FYI, oracle and task.cheat(...) functions are the same thing.

Hope this helps!
Alex

**Comment by dgjun32** [comment]
Thank you so much! 

Additional question is:

```
def extract_trace(task_cls, headless=True):
    """
    Extracts the trace of actions and observations for a given task.

    Parameters:
    ------------
    task_cls: class
        The class of the task to extract the trace from.

    """
    # Instantiate a new environment
    env = BrowserEnv(task_entrypoint=task_cls, headless=headless, slow_mo=1000)

    # Setup customized tracing
    trace = []
    monkey_patch_playwright(observation_callback=env._get_obs, trace_storage=trace)

    env.reset()
    env.task.cheat(env.page, env.chat.messages)
    env.close()

    return trace
```
In this script, how can I specify an individual task instance? As far as I understood, there are 33 task types and 10~1000 unique tasks are available for each task type. Can I use seed parameter when reset the environment?
