### ISSUE TITLE
Error in the cheat function (oracle solver)

### ISSUE THREAD

**Issue by dgjun32** [ServiceNow/WorkArena#28]
I observed error of oracle in several task types: mainly in sort & filter task types in List category.

For example, in 18 th episode of workarena.servicenow.sort-user-list task type, 
action sequence proposed by oracle is:
 
click('a46') -> click('a1005') -> **select_option('a1183', 'Department')** -> select_option('a1240', 'descending') -> click('a1005'). 

However, the strange thing is that there is no element corresponding to bid 'a1183' in third observation, and also when running this action sequence in Workarena environment,  execution error occurs (as a1183 does not exists in the third observation).

**Comment by dgjun32** [comment]
Hello, is there any update on this issue?

**Comment by aldro61** [comment]
Hi @dgjun32, I'm not sure what you are referring to. The Oracle functions (.cheat) rely on Playwright code, not BrowserGym primitives. Can you provide more context? Where are you facing this problem?

**Comment by optimass** [comment]
Hi @dgjun32,

There's no guarantee that the bids used by the Oracle will also be present in the AX tree that the agent observes.

hope this helps!

**Comment by dgjun32** [comment]
Hi @aldro61, I am referring to the code in `src/wa_action_traces.py`.

**Comment by dgjun32** [comment]
@optimass, Thanks for the answer. 
I am trying to extract a oracle demonstration for fine-tuning the LLM agent.
However, if bids used by the Oracle is not present in the AX tree that the agent observes, then is it a valid demonstration?
For example, oracle action at time step t is click(bid='a1300'), and the bid 'a1300' does not exist in the observation at time step t, then what does the 'a1300' means?

**Comment by optimass** [comment]
@gasse can you clarify my point please?

**Comment by gasse** [comment]
Hi all. Yes that's something we've already identified. Basically the oracle (`cheat()` function) might click on generic elements like div and span, but these elements are not rendered by the `flatten_axtree_to_str()` method by default. So you don't see their bids in the AXTree.

@dgjun32 can you try printing the AXTree with `skip_generic=False` instead? I think then you should see the missing bids.
https://github.com/ServiceNow/BrowserGym/blob/89eccd555f413112c4e7687b5395ffd1f2c00862/browsergym/core/src/browsergym/utils/obs.py#L287
