### ISSUE TITLE
Curriculum seeds

### ISSUE THREAD

**Issue by gasse** [ServiceNow/WorkArena#35]
When generating pairs of (task, seed) it seems all tasks in the same bucket receive the same seed. Is it expected?
https://github.com/ServiceNow/WorkArena/blob/ea8462dc96001c0a37d0ecc4e626f9c1339ee85f/src/browsergym/workarena/__init__.py#L159

**Comment by Megh-Thakkar** [comment]
Hi Max, yes we generate a number of seeds in total based on the curriculum and all the tasks will have the same “num_seeds” for a bucket.

**Comment by gasse** [comment]
Got it. I think it's ok since you draw tasks without replacement, i.e. you will never pick twice the same task name with the same seed. Thanks!
