### ISSUE TITLE
Extracted fine-tuning trace does not work in task environment.

### ISSUE THREAD

**Issue by dgjun32** [ServiceNow/WorkArena#37]
Hello, I have an issue with extraction of oracle trace for fine-tuning LLM agent.

As mentioned in the paper, there is a code to extract oracle trace for tasks in WorkArena L1 task types (`src/wa_action_traces.py`).
Although it provides obs-action trace for each task instance, I found a few problems.

The problem occured in a specific task types: entire sort / filter task types, impersonation tasks, a few form-filling tasks.

1. When I simply execute the extracted oracle action sequence in the task environment, episode ends in failure due to consecutive inadmissible actions.

2. To analyze the reason, I inspected the extracted trace, and I found that bid in action is not included in the corresponding axtree observation. However, I observed that the bid (in action) exists in the DOM object of the observation.

Therefore, It seems oracle trace extraction is slightly unreliable especially in sort & filter task types. 
How can I collect valid demonstration (trace) data for fine-tuning the LLM agent?

**Comment by aldro61** [comment]
Duplicated of #28

**Comment by aldro61** [comment]
Closing but referencing in #28.
