### ISSUE TITLE
Using it for offline environment

### ISSUE THREAD

**Issue by Shape-Kim** [ServiceNow/WorkArena#46]
First of all, thank you for your beautiful work. I am truly impressed by it!

I would like to implement your project in an offline environment without internet access.

Is it possible to implement in the offline? 

Thank you again for your great work.

**Comment by aldro61** [comment]
Hi @Shape-Kim, thank you for the kind words! Unfortunately, this would not be possible as it would require having an offline copy of the ServiceNow product (which we cannot provide).

To learn more about the benchmark, you can check this recent lecture: https://www.youtube.com/live/-yf-e-9FvOc?si=YMw0GZHLc82e61eG&t=2390. I explain that the ServiceNow product is closed source, while the benchmark is open source.

Best,
Alex

**Comment by Shape-Kim** [comment]
I really appreciate the quck reply. 

Thank you!

Best regards,
Dohyung Kim
